In [2]:
import numpy as np

In [10]:
array_1d = np.array([1, 2, 3, 4, 5], dtype=int)

print("1D Array:")
print(array_1d)
print("Boyut:", array_1d.ndim)
print("Eleman sayısı:", array_1d.size)
print("Shape:", array_1d.shape)

1D Array:
[1 2 3 4 5]
Boyut: 1
Eleman sayısı: 5
Shape: (5,)


In [14]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

print("2D Array:")
print(array_2d)
print("Boyut:", array_2d.ndim)
print("Eleman sayısı:", array_2d.size)
print("Shape (satır, sütun):", array_2d.shape)

2D Array:
[[1 2 3]
 [4 5 6]]
Boyut: 2
Eleman sayısı: 6
Shape (satır, sütun): (2, 3)


In [16]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype=int)

print("3D Array:")
print(array_3d)
print("Boyut:", array_3d.ndim)
print("Eleman sayısı:", array_3d.size)
print("Shape (derinlik, satır, sütun):", array_3d.shape)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Boyut: 3
Eleman sayısı: 12
Shape (derinlik, satır, sütun): (2, 2, 3)


In [36]:
array_1d[0]

1

In [38]:
array_1d[:3]

array([1, 2, 3])

In [49]:
array_2d[0, :]

array([1, 2, 3])

In [47]:
array_2d[:, 0]

array([1, 4])

In [45]:
array_2d[1, 1]

5

In [51]:
array_3d[0, :, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
array_3d[:, 0, 0]

array([1, 7])

In [57]:
zeros_array = np.zeros((2, 3), dtype=int)
ones_array = np.ones((2, 3), dtype=int)

row_concat = np.vstack((zeros_array, ones_array))
print("\nSatır bazında birleştirme:")
print(row_concat)

col_concat = np.hstack((zeros_array, ones_array))
print("\nSütun bazında birleştirme:")
print(col_concat)


Satır bazında birleştirme:
[[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]

Sütun bazında birleştirme:
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
